base_url = "https://pascal.japati.net/"
title = "My Daily Babbling"
description = "I simply write what I think, so if I stopped writing—I stopped thinking."

compile_sass = true
generate_feeds = true
minify_html = true
build_search_index = false
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
# highlight_theme = "ayu-light"

[extra]
author = "Pascal Hadiyanto"
github = "https://github.com/L1so"
email = "pascal@japati.net"
timeformat = "%B %e, %Y"                   # e.g. June 14, 2021

[[extra.menu]]
name = "Archive"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"

[extra.footer]
info = 'Powered by <a href="https://www.getzola.org" target="_blank">Zola</a> and <a href="https://github.com/semanticdata/mabuya">Mabuya</a>.'
